services:
  - type: web
    name: imageclassifier
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
